"""
pipeline.py
-----------
Stage 6 — Pipeline Orchestrator

Single entry point for the entire resume ingestion pipeline.
This is the only function the Django backend calls.

Wires all 5 stages in order:
    Stage 1 → blob_service  : Upload CV → Blob Storage, generate SAS URL
    Stage 2 → extractor     : File bytes → Document Intelligence → raw text
    Stage 3 → structurer    : Raw text → GPT-4o → structured JSON + embeddingText
    Stage 4 → embedder      : embeddingText → text-embedding-3-small → vector
    Stage 5 → writer        : Dual write → Cosmos DB + AI Search

Django integration:
    from resume_pipeline.pipeline import process_resume

    result = process_resume(
        file_bytes    = request.FILES["cv"].read(),
        file_extension = "pdf",
        candidate_id  = str(uuid.uuid4()),
    )
    # result = {"candidateId": "...", "cosmosDocumentId": "...", "status": "completed"}

processingStatus lifecycle:
    "pending"     → set by pipeline before Stage 1 (not written — Django sets this if needed)
    "processing"  → set by writer.py at Cosmos write time
    "completed"   → set by writer.py after both stores confirm success
    "failed"      → set by writer.py if Search write fails after Cosmos write
                    OR raised as exception here for pre-write failures (Stages 1–4)
"""

from resume_pipeline.blob_service import upload_cv_and_get_url
from resume_pipeline.extractor    import extract_text
from resume_pipeline.structurer   import structure_resume
from resume_pipeline.embedder     import generate_embedding
from resume_pipeline.writer       import write_candidate


def process_resume(
    file_bytes:     bytes,
    file_extension: str,
    candidate_id:   str,
) -> dict:
    """
    Run the full resume ingestion pipeline end-to-end.

    Args:
        file_bytes:     Raw bytes of the uploaded CV (PDF or DOCX)
        file_extension: 'pdf' or 'docx' (without dot)
        candidate_id:   UUID4 string — must be generated by caller (Django view)
                        Used as the shared key across Blob Storage, Cosmos DB, AI Search

    Returns:
        {
            "candidateId":      str,   ← shared key — store this in Django session/DB
            "cosmosDocumentId": str,   ← same as candidateId (Phase 1)
            "status":           "completed"
        }

    Raises:
        Exception with stage label if any step fails.
        Stage 5 partial failures are handled internally by writer.py —
        Cosmos DB processingStatus is updated to "failed" before raising.

    Cost per call (approximate):
        Document Intelligence: ~$0.001 per page
        GPT-4o:                ~$0.01–0.03 per resume
        text-embedding-3-small: ~$0.00002 per call
        Cosmos DB write:        ~1 RU (serverless)
        AI Search upload:       negligible
    """

    # ── Stage 1 — Upload to Blob Storage ──────────────────────────────────────
    try:
        blob_result = upload_cv_and_get_url(file_bytes, candidate_id, file_extension)
        sas_url     = blob_result["sas_url"]
    except Exception as e:
        raise Exception(f"[Stage 1 — Blob Upload] Failed for candidate '{candidate_id}': {e}") from e

    # ── Stage 2 — Extract text via Document Intelligence ──────────────────────
    try:
        raw_text = extract_text(file_bytes, file_extension)
    except Exception as e:
        raise Exception(f"[Stage 2 — Document Intelligence] Failed for candidate '{candidate_id}': {e}") from e

    # ── Stage 3 — Structure via GPT-4o ────────────────────────────────────────
    try:
        structure_result = structure_resume(raw_text)
        structured_json  = structure_result["structuredJson"]
        embedding_text   = structure_result["embeddingText"]
    except Exception as e:
        raise Exception(f"[Stage 3 — GPT-4o Structuring] Failed for candidate '{candidate_id}': {e}") from e

    # ── Stage 4 — Generate embedding vector ───────────────────────────────────
    try:
        vector = generate_embedding(embedding_text)
    except Exception as e:
        raise Exception(f"[Stage 4 — Embedding] Failed for candidate '{candidate_id}': {e}") from e

    # ── Stage 5 — Dual write: Cosmos DB + AI Search ───────────────────────────
    # writer.py handles its own partial failure — Cosmos is patched to "failed"
    # if Search write fails. Exception is still raised to the caller.
    try:
        result = write_candidate(
            candidate_id    = candidate_id,
            raw_text        = raw_text,
            structured_json = structured_json,
            embedding_text  = embedding_text,
            vector          = vector,
            sas_url         = sas_url,
        )
    except Exception as e:
        raise Exception(f"[Stage 5 — Write] Failed for candidate '{candidate_id}': {e}") from e

    return result